version: '3'
services:
  node1:
    build:
        dockerfile: Dockerfile.dev
        context: .
    ports:
      - "18332:18332"
      - "18333:18333"
      - "28332:28332"
    expose: 
      - "18332"
      - "18333"
      - "28332"
    command: [ "-addnode=node2:18333", "-addnode=node3:18333", "-zmqpubhashblock=tcp://*:28332", "-zmqpubhashtx=tcp://*:28332"]
  node2:
    build:
        dockerfile: Dockerfile.dev
        context: .
    ports:
      - "18501:18333"
    expose: 
      - "18333"
    command: [ "-addnode=node1:18333", "-addnode=node3:18333"]
  node3:
    build:
        dockerfile: Dockerfile.dev
        context: .
    ports:
      - "18502:18333"
    expose: 
      - "18333"
    command: [ "-addnode=node2:18333", "-addnode=node1:18333"]

    curl -d '{"utxo": {"txid":"94b5c6ada76159c13b44028bde51a229ae078a04d98cb6e939abc0c3cd1f2513", "vout”:1, "scriptPubKey": "76a9146809443e06872cc9236b61ac73645013d1fe8e0088ac","satoshis":5000000000}}' -H "Content-Type: application/json" -X POST http://localhost:8003/splitting/split